use rand;

pub mod quotes {
    const QUOTES: [&str; 76] = [
      "\"The only way to do great work is to love what you do.\" - Steve Jobs",
      "\"In three words I can sum up everything I've learned about life: it goes on.\" - Robert Frost",
      "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt",
      "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela",
      "\"The only limit to our realization of tomorrow will be our doubts of today.\" - Franklin D. Roosevelt",
      "\"Life is what happens when you're busy making other plans.\" - John Lennon",
      "\"The journey of a thousand miles begins with one step.\" - Lao Tzu",
      "\"Success is not final, failure is not fatal: It is the courage to continue that counts.\" - Winston Churchill",
      "\"In the end, we will remember not the words of our enemies, but the silence of our friends.\" - Martin Luther King Jr.",
      "\"The only thing we have to fear is fear itself.\" - Franklin D. Roosevelt",
      "\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\" - Ralph Waldo Emerson",
      "\"The best revenge is massive success.\" - Frank Sinatra",
      "\"It does not matter how slowly you go as long as you do not stop.\" - Confucius",
      "\"The only way to do great work is to love what you do.\" - Steve Jobs",
      "\"The only thing standing between you and your dream is the will to try and the belief that it is actually possible.\" - Joel Brown",
      "\"Don't watch the clock; do what it does. Keep going.\" - Sam Levenson",
      "\"Life is 10% what happens to us and 90% how we react to it.\" - Charles R. Swindoll",
      "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela",
      "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt",
      "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
      "\"It always seems impossible until it's done.\" - Nelson Mandela",
      "\"Success is walking from failure to failure with no loss of enthusiasm.\" - Winston Churchill",
      "\"Believe you can and you're halfway there.\" - Theodore Roosevelt",
      "\"I have not failed. I've just found 10,000 ways that won't work.\" - Thomas A. Edison",
      "\"The only limit to our realization of tomorrow will be our doubts of today.\" - Franklin D. Roosevelt",
      "\"If you want to achieve greatness stop asking for permission.\" - Anonymous",
      "\"The journey of a thousand miles begins with one step.\" - Lao Tzu",
      "\"It's not whether you get knocked down, it's whether you get up.\" - Vince Lombardi",
      "\"The harder the conflict, the greater the triumph.\" - George Washington",
      "\"I have learned over the years that when one's mind is made up, this diminishes fear.\" - Rosa Parks",
      "\"You must be the change you wish to see in the world.\" - Mahatma Gandhi",
      "\"In the midst of winter, I found there was, within me, an invincible summer.\" - Albert Camus",
      "\"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.\" - Joel Brown",
      "\"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.\" - Albert Einstein",
      "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Ralph Waldo Emerson",
      "\"I attribute my success to this: I never gave or took any excuse.\" - Florence Nightingale",
      "\"Your time is limited, don't waste it living someone else's life.\" - Steve Jobs",
      "\"Life is a journey that must be traveled no matter how bad the roads and accommodations.\" - Oliver Goldsmith",
      "\"If you want to lift yourself up, lift up someone else.\" - Booker T. Washington",
      "\"The only thing we have to fear is fear itself.\" - Franklin D. Roosevelt",
      "\"It does not matter how slowly you go as long as you do not stop.\" - Confucius",
      "\"I am not a product of my circumstances. I am a product of my decisions.\" - Stephen Covey",
      "\"The best time to plant a tree was 20 years ago. The second best time is now.\" - Chinese Proverb",
      "\"Don't judge each day by the harvest you reap but by the seeds that you plant.\" - Robert Louis Stevenson",
      "\"It is during our darkest moments that we must focus to see the light.\" - Aristotle Onassis",
      "\"The only way to do great work is to love what you do.\" - Steve Jobs",
      "\"Life is really simple, but we insist on making it complicated.\" - Confucius",
      "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela",
      "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
      "\"The future belongs to those who believe in the beauty of their dreams.\" - Eleanor Roosevelt",
      "\"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\" - Ralph Waldo Emerson",
      "\"I have learned over the years that when one's mind is made up, this diminishes fear.\" - Rosa Parks",
      "\"The journey of a thousand miles begins with one step.\" - Lao Tzu",
      "\"Success is not final, failure is not fatal: It is the courage to continue that counts.\" - Winston Churchill",
      "\"The only limit to our realization of tomorrow will be our doubts of today.\" - Franklin D. Roosevelt",
      "\"In the end, we will remember not the words of our enemies, but the silence of our friends.\" - Martin Luther King Jr.",
      "\"It always seems impossible until it's done.\" - Nelson Mandela",
      "\"Believe you can and you're halfway there.\" - Theodore Roosevelt",
      "\"Don't watch the clock; do what it does. Keep going.\" - Sam Levenson",
      "\"The harder the conflict, the greater the triumph.\" - George Washington",
      "\"I have not failed. I've just found 10,000 ways that won't work.\" - Thomas A. Edison",
      "\"Life is 10% what happens to us and 90% how we react to it.\" - Charles R. Swindoll",
      "\"The only thing standing between you and your dream is the will to try and the belief that it is actually possible.\" - Joel Brown",
      "\"You must be the change you wish to see in the world.\" - Mahatma Gandhi",
      "\"In the midst of winter, I found there was, within me, an invincible summer.\" - Albert Camus",
      "\"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.\" - Albert Einstein",
      "\"Your time is limited, don't waste it living someone else's life.\" - Steve Jobs",
      "\"Life is a journey that must be traveled no matter how bad the roads and accommodations.\" - Oliver Goldsmith",
      "\"If you want to lift yourself up, lift up someone else.\" - Booker T. Washington",
      "\"The only thing we have to fear is fear itself.\" - Franklin D. Roosevelt",
      "\"It does not matter how slowly you go as long as you do not stop.\" - Confucius",
      "\"I am not a product of my circumstances. I am a product of my decisions.\" - Stephen Covey",
      "\"The best time to plant a tree was 20 years ago. The second best time is now.\" - Chinese Proverb",
      "\"Don't judge each day by the harvest you reap but by the seeds that you plant.\" - Robert Louis Stevenson",
      "\"It is during our darkest moments that we must focus to see the light.\" - Aristotle Onassis",
      "\"Life is really simple, but we insist on making it complicated.\" - Confucius"
    ];

    pub fn get_random_quote() -> &'static str {
        //pick a random quote using a random number generator
        QUOTES[rand::random::<usize>() % QUOTES.len()]
    }
}
